version: '3.9'

volumes:
  packages:
  out:

services:
  scratcher:
    build:
      context: ./scratcher
    container_name: scratcher
    tty: true
    volumes:
      - type: bind
        source: ./scratcher
        target: /works
      - type: volume
        source: packages
        target: /usr/local/lib/python3.9/site-packages
      - type: volume
        source: out
        target: /works/out

